# docker-compose.yml
services:
  ollama:
    # Use your custom Dockerfile to build the Ollama service
    build:
      context: ./ollama_server
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ollama_models:/root/.ollama/models
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 60s
      timeout: 15s
      retries: 5
      start_period: 120s # Good for initial model download, can be reduced later
    deploy: # for laptop nvidia GPU support if not available comment out
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      my_bridge_network: # Assign to the custom network

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883" # Standard MQTT port
      - "9001:9001" # WebSocket port (optional, for web clients)
    volumes:
      - ./mosquitto_config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_logs:/mosquitto/log
    command: mosquitto -c /mosquitto/config/mosquitto.conf
    # user: "0" # REMOVE OR COMMENT OUT THIS LINE - ensure it's removed if you added it for testing
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mosquitto_sub -t '$$SYS/broker/version' -C 1 || exit 1"]
      interval: 60s
      timeout: 5s
      retries: 5
    networks:
      my_bridge_network: # Mosquitto will now get an IP from the 'my_bridge_network' pool automatically

  mcp_server:
    build: ./mcp_server
    container_name: mcp_server
    ports:
      - "4000:4000"
    env_file:
      - .env # <--- Make sure this line exists!
    environment:
      PYTHONUNBUFFERED: 1
      OPENWEATHER_API_KEY: ${OPENWEATHER_API_KEY} # <--- Make sure this line exists!
    networks:
      my_bridge_network: # MCP Server will now get an IP from the 'my_bridge_network' pool automatically
    healthcheck: # Add a healthcheck for MCP Server too!
      test: ["CMD-SHELL", "curl -f http://localhost:4000/docs || exit 1"] # Or /ping if you add one
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 30s

  adk_app:
    build:
      context: ./adk_ollama_tool
      dockerfile: Dockerfile.adk
    container_name: adk_app
    ports:
      - "8000:8000" # Expose 8000 for internal communication with dashboard
    env_file:
      - .env
    environment:
      OLLAMA_BASE_URL: http://ollama:11434 # Communication by service name
      MCP_SERVER_URL: http://mcp_server:4000 # Communication by service name
      OPENWEATHER_API_KEY: ${OPENWEATHER_API_KEY} # Ensure this is set in your .env file
      MQTT_BROKER_HOST: mosquitto # <--- IMPORTANT CHANGE: Use service name 'mosquitto'
      MQTT_BROKER_PORT: 1883
      PYTHONUNBUFFERED: 1
    depends_on:
      ollama:
        condition: service_healthy
      mosquitto:
        condition: service_healthy
      mcp_server:
        condition: service_healthy
    restart: unless-stopped
    networks:
      my_bridge_network: # Assign to the custom network
    healthcheck: # <--- ADD THIS HEALTHCHECK BLOCK
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health/ || exit 1"]
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 60s # Give it some time to fully initialize and connect to other services

  dashboard_server:
    build:
      context: ./dashboard_server
      dockerfile: Dockerfile.dashboard
    container_name: dashboard_server
    ports:
      - "6000:6000" # Expose 6000 for the dashboard
    env_file:
      - .env
    environment:
      ADK_APP_URL: http://adk_app:8000 # This is how dashboard_server finds adk_app
    depends_on:
      adk_app:
        condition: service_healthy # This condition now has a healthcheck to wait for
    restart: unless-stopped
    networks:
      my_bridge_network: # Join the custom network

volumes:
  ollama_data:
  ollama_models:
  mosquitto_data:
  mosquitto_logs:

# Define your custom network (no static IP config for the network itself)
networks:
  my_bridge_network:
    driver: bridge
    # The 'ipam' section defining specific subnet and gateway is removed.
    # Docker will now choose a suitable subnet automatically for this bridge network.