# adk_ollama_tool/Dockerfile.adk
FROM python:3.11-slim

WORKDIR /app

# Add curl
RUN apt-get update && apt-get install -y curl && apt-get clean

COPY requirements.txt ./
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
