# dashboard_server/Dockerfile.dashboard
FROM python:3.9-slim-buster

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY ./main.py /app/main.py
COPY ./templates /app/templates
COPY ./static /app/static 

# Expose the port FastAPI will run on
EXPOSE 8000

# Command to run the FastAPI application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "6000"]